version: "3.3"
services:
  report:
    build: .
    image: jira-report
    environment:
      - PYTHONUNBUFFERED=true
      #- REFLEX_APIKEY=jira-report.asdfasdf
      #- REFLEX_URL=https://reflex.thesite/api/v1
